import { Inter } from "next/font/google";
import "../style/globals.css";
import DataProvider from "@/redux/store";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Loading from "./loading";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>

      <DataProvider>
      <Suspense fallback={<Loading />}>
      <Layout>
        {children}
      </Layout>
      </Suspense>
      </DataProvider>
      <Toaster/>
      </body>
    </html>
  );
}
